//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHastane.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_HastaneYonetimSistemiEntities : DbContext
    {
        public db_HastaneYonetimSistemiEntities()
            : base("name=db_HastaneYonetimSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Doktorlar> tbl_Doktorlar { get; set; }
        public virtual DbSet<tbl_Hasta> tbl_Hasta { get; set; }
        public virtual DbSet<tbl_Randevu> tbl_Randevu { get; set; }
        public virtual DbSet<tbl_Tedavi> tbl_Tedavi { get; set; }
    }
}
