//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHastane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doktorlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Doktorlar()
        {
            this.tbl_Randevu = new HashSet<tbl_Randevu>();
            this.tbl_Tedavi = new HashSet<tbl_Tedavi>();
        }
    
        public int doktorID { get; set; }
        public string doktorAd { get; set; }
        public string doktorSoyad { get; set; }
        public string doktorUzmanlik { get; set; }
        public Nullable<bool> durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Randevu> tbl_Randevu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tedavi> tbl_Tedavi { get; set; }
    }
}
