//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHastane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Hasta()
        {
            this.tbl_Randevu = new HashSet<tbl_Randevu>();
            this.tbl_Tedavi = new HashSet<tbl_Tedavi>();
        }
    
        public int hastaID { get; set; }
        public string hastaAd { get; set; }
        public string hastaSoyad { get; set; }
        public string hastaTc { get; set; }
        public Nullable<byte> hastaYas { get; set; }
        public string hastaCinsiyet { get; set; }
        public Nullable<bool> kronikRahatsizlik { get; set; }
        public string hastaTelefon { get; set; }
        public Nullable<System.DateTime> kayitTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Randevu> tbl_Randevu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tedavi> tbl_Tedavi { get; set; }
    }
}
