//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHastane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Randevu
    {
        public int randevuID { get; set; }
        public Nullable<int> hastaID { get; set; }
        public Nullable<int> doktorID { get; set; }
        public Nullable<System.DateTime> olusturmaTarih { get; set; }
        public Nullable<System.DateTime> randevuTarih { get; set; }
    
        public virtual tbl_Doktorlar tbl_Doktorlar { get; set; }
        public virtual tbl_Hasta tbl_Hasta { get; set; }
    }
}
